/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const FormLazyRouteImport = createFileRoute('/form')()
const DetailsLazyRouteImport = createFileRoute('/details')()
const IndexLazyRouteImport = createFileRoute('/')()

const FormLazyRoute = FormLazyRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))
const DetailsLazyRoute = DetailsLazyRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/details.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/details': typeof DetailsLazyRoute
  '/form': typeof FormLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/details': typeof DetailsLazyRoute
  '/form': typeof FormLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/details': typeof DetailsLazyRoute
  '/form': typeof FormLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details' | '/form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details' | '/form'
  id: '__root__' | '/' | '/details' | '/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DetailsLazyRoute: typeof DetailsLazyRoute
  FormLazyRoute: typeof FormLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DetailsLazyRoute: DetailsLazyRoute,
  FormLazyRoute: FormLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
